export const suggestedIngredients = {
  "meat&proteins": [
    "chicken",
    "beef",
    "duck",
    "lamb",
    "turkey",
    "pork",
    "fish",
    "tofu",
    "eggs",
  ],
  vegetables: [
    "asparagus",
    "broccoli",
    "bell peppers",
    "beans",
    "cabbage",
    "cucumbers",
    "carrots",
    "potatoes",
    "sweet potatoes",
    "onions",
    "spinach",
    "mushrooms",
    "garlic",
    "zucchini",
  ],
  spices: [
    "cardamon",
    "cumin",
    "cinnamon",
    "coriander",
    "cayenne",
    "clove",
    "curry",
    "chilli",
    "salt",
    "pepper",
    "paprika",
    "basil",
    "yhyme",
    "oregano",
    "ginger",
    "garlic powder",
    "thyme",
    "parsley",
  ],
  fruits: ["tomatoes", "lemons", "apples", "bananas", "berries", "oranges"],
  dairy: [
    "milk",
    "cheese",
    "butter",
    "yogurt",
    "cream",
    "ice cream",
    "kefir",
    "whey",
    "sour cream",
    "ghee",
  ],
  grains: [
    "rice",
    "pasta",
    "lentils",
    "chickpeas",
    "quinoa",
    "bread",
    "oats",
    "arroz",
    "farro",
    "granola",
  ],
  condiments: [
    "soy sauce",
    "vinegar",
    "ketchup",
    "mayonnaise",
    "mustard",
    "honey",
    "hot sauce",
    "salsa",
    "barbecue sauce",
    "nut butter",
    "wasabi",
    "pesto",
    "guacamole",
    "dijon mustard",
    "hummus",
  ],
  nuts: [
    "almonds",
    "walnuts",
    "sunflower seeds",
    "pumpkin seeds",
    "chia seeds",
    "macadamia nuts",
    "pecans",
    "cashews",
    "hazelnuts",
    "sesame seeds",
    "pistachios",
  ],
};
